# Podfile content
 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '8.0'

 target 'TampereApp' do
   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
   pod 'React', path: '../node_modules/react-native', :subspecs => [
     'Core',
     'RCTActionSheet',
     'RCTAnimation',
     'RCTGeolocation',
     'RCTImage',
     'RCTLinkingIOS',
     'RCTNetwork',
     'RCTSettings',
     'RCTText',
     'RCTVibration',
     'RCTWebSocket',
     'BatchedBridge'
   ]
   pod 'GoogleMaps'
   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

   pod 'AppAuth', '>= 0.91'
   pod 'react-native-maps', :path => '../node_modules/react-native-maps'

   pod 'RNSVG', :path => '../node_modules/react-native-svg'

 end

 post_install do |installer|
   installer.pods_project.targets.each do |target|
     if target.name == 'react-native-google-maps'
       target.build_configurations.each do |config|
         config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
       end
     end
   end
 end
